"""
Module 4: Team Analytics Dashboard — core service logic.

Aggregates review data (Module 2) and bug triage data (Module 3)
to compute team velocity metrics, code churn hotspots, and generate
a concise AI weekly summary for Team Leads and Admins.
"""

import json
from datetime import datetime, timedelta, timezone

from app.db import get_connection
from app.services import llm_service


AI_SUMMARY_SYSTEM = """You are DevSphere's Team Analytics module. Given the metrics below, write a \
concise 2-3 sentence summary of team velocity and any concerning trends a Team Lead \
should know about. Be specific, reference the actual numbers."""


def _get_cutoff_date(period: str) -> datetime:
    """Calculates the cutoff timestamp for the requested period."""
    now = datetime.now(timezone.utc)
    p = period.lower().strip()
    if p == "7d":
        return now - timedelta(days=7)
    elif p == "30d":
        return now - timedelta(days=30)
    elif p == "90d":
        return now - timedelta(days=90)
    else:
        # Default to 7 days if unrecognized
        return now - timedelta(days=7)


def get_team_analytics(repo_key: str, period: str = "7d") -> dict:
    """
    Computes all analytics metrics for a given repo over the specified time window:
      1. PR turnaround time and review counts (Module 2)
      2. Bug resolution metrics and severity distribution (Module 3)
      3. Code churn hotspots across reviews and bugs
      4. Executive natural-language summary generated by Gemini (FR-4)
    """
    cutoff = _get_cutoff_date(period)
    conn = get_connection()

    try:
        with conn.cursor() as cur:
            # ─────────────────────────────────────────────
            # 1. PR Reviews Metrics (Module 2)
            # ─────────────────────────────────────────────
            cur.execute(
                """
                SELECT id, pr_number, status, issues_found, created_at
                FROM pr_reviews
                WHERE repo_full_name = %s AND created_at >= %s
                ORDER BY created_at DESC
                """,
                (repo_key, cutoff),
            )
            review_rows = cur.fetchall()

            total_reviews = len(review_rows)
            completed_reviews = sum(1 for r in review_rows if r[2] == "completed")
            failed_reviews = sum(1 for r in review_rows if r[2] == "failed")
            unique_prs = len(set(r[1] for r in review_rows))
            total_review_issues = sum((r[3] or 0) for r in review_rows)

            # Compute real average PR turnaround time in hours.
            # For each distinct PR, find spread between earliest and latest review
            # timestamp. Average across all PRs that had >1 review run.
            pr_timestamps: dict = {}
            for row in review_rows:
                pr_num = row[1]
                ts = row[4]  # created_at (TIMESTAMP without TZ, stored as UTC)
                if ts is None:
                    continue
                if pr_num not in pr_timestamps:
                    pr_timestamps[pr_num] = [ts, ts]
                else:
                    if ts < pr_timestamps[pr_num][0]:
                        pr_timestamps[pr_num][0] = ts
                    if ts > pr_timestamps[pr_num][1]:
                        pr_timestamps[pr_num][1] = ts

            turnaround_list = []
            for earliest, latest in pr_timestamps.values():
                diff = (latest - earliest).total_seconds() / 3600
                turnaround_list.append(diff)

            avg_pr_turnaround_hours = (
                round(sum(turnaround_list) / len(turnaround_list), 1)
                if turnaround_list
                else 0.0
            )

            # ─────────────────────────────────────────────
            # 2. Bug Triage Metrics (Module 3)
            # ─────────────────────────────────────────────
            cur.execute(
                """
                SELECT bug_id, severity, COALESCE(status, 'open'), affected_files, created_at
                FROM bugs
                WHERE repo_key = %s AND created_at >= %s
                ORDER BY created_at DESC
                """,
                (repo_key, cutoff),
            )
            bug_rows = cur.fetchall()

            total_bugs = len(bug_rows)
            bugs_by_sev = {"low": 0, "medium": 0, "high": 0}
            bugs_resolved = 0
            bugs_open = 0
            bug_files_list = []

            for row in bug_rows:
                sev = str(row[1] or "medium").lower()
                if sev in bugs_by_sev:
                    bugs_by_sev[sev] += 1
                else:
                    bugs_by_sev["medium"] += 1

                st = str(row[2] or "open").lower()
                if st == "resolved":
                    bugs_resolved += 1
                else:
                    bugs_open += 1

                if row[3] and isinstance(row[3], list):
                    bug_files_list.extend(row[3])

            bugs_resolved_pct = (
                round((bugs_resolved / total_bugs) * 100, 1) if total_bugs > 0 else 100.0
            )

            # ─────────────────────────────────────────────
            # 3. Code Churn Hotspots (FR-3)
            # ─────────────────────────────────────────────
            # From PR review comments:
            cur.execute(
                """
                SELECT prc.file_path, COUNT(*)
                FROM pr_review_comments prc
                JOIN pr_reviews pr ON pr.id = prc.review_id
                WHERE pr.repo_full_name = %s AND pr.created_at >= %s
                GROUP BY prc.file_path
                """,
                (repo_key, cutoff),
            )
            pr_comment_rows = cur.fetchall()

            churn_map = {}
            for path, count in pr_comment_rows:
                if not path:
                    continue
                churn_map[path] = churn_map.get(path, {"file": path, "review_issues": 0, "bug_reports": 0})
                churn_map[path]["review_issues"] += count

            for path in bug_files_list:
                if not path:
                    continue
                churn_map[path] = churn_map.get(path, {"file": path, "review_issues": 0, "bug_reports": 0})
                churn_map[path]["bug_reports"] += 1

            top_churn_files = []
            for path, item in churn_map.items():
                total_churn = item["review_issues"] + item["bug_reports"]
                top_churn_files.append({
                    "file": path,
                    "count": total_churn,
                    "review_issues": item["review_issues"],
                    "bug_reports": item["bug_reports"],
                })

            top_churn_files.sort(key=lambda x: x["count"], reverse=True)
            top_churn_files = top_churn_files[:8]

    finally:
        conn.close()

    # ─────────────────────────────────────────────
    # 4. Generate AI Executive Summary (FR-4)
    # ─────────────────────────────────────────────
    ai_summary = _generate_ai_summary(
        repo_key=repo_key,
        period=period,
        avg_turnaround=avg_pr_turnaround_hours,
        prs_reviewed=total_reviews,
        unique_prs=unique_prs,
        bugs_total=total_bugs,
        bugs_open=bugs_open,
        bugs_resolved=bugs_resolved,
        bugs_resolved_pct=bugs_resolved_pct,
        bugs_by_sev=bugs_by_sev,
        top_churn=top_churn_files,
    )

    return {
        "repo_key": repo_key,
        "period": period,
        "avg_pr_turnaround_hours": avg_pr_turnaround_hours,
        "prs_reviewed": total_reviews,
        "prs_completed": completed_reviews,
        "prs_failed": failed_reviews,
        "prs_merged": unique_prs,
        "bugs_total": total_bugs,
        "bugs_resolved": bugs_resolved,
        "bugs_open": bugs_open,
        "bugs_resolved_pct": bugs_resolved_pct,
        "bug_severity_breakdown": bugs_by_sev,
        "top_churn_files": top_churn_files,
        "ai_summary": ai_summary,
    }


def _generate_ai_summary(
    repo_key: str,
    period: str,
    avg_turnaround: float,
    prs_reviewed: int,
    unique_prs: int,
    bugs_total: int,
    bugs_open: int,
    bugs_resolved: int,
    bugs_resolved_pct: float,
    bugs_by_sev: dict,
    top_churn: list,
) -> str:
    """Calls Gemini to generate a concise 2-3 sentence executive summary."""
    top_files_summary = (
        ", ".join(f"{c['file']} ({c['count']} flags)" for c in top_churn[:3])
        if top_churn
        else "no concentrated hotspots"
    )

    prompt = (
        f"METRICS FOR REPOSITORY: {repo_key} (Period: {period})\n"
        f"- Pull Requests: {unique_prs} distinct PRs reviewed ({prs_reviewed} review runs total).\n"
        f"- Average Turnaround: {avg_turnaround} hours.\n"
        f"- Bug Triage: {bugs_total} total reported bugs ({bugs_by_sev['high']} High, {bugs_by_sev['medium']} Medium, {bugs_by_sev['low']} Low).\n"
        f"- Resolution Progress: {bugs_resolved} resolved ({bugs_resolved_pct}%), {bugs_open} currently open.\n"
        f"- Code Churn Hotspots: {top_files_summary}.\n\n"
        "Write a concise 2-3 sentence summary for the Team Lead about team velocity, resolution rate, and any concerning hotspots. Be specific and reference the actual numbers."
    )

    try:
        summary = llm_service.generate_raw(
            prompt=prompt,
            system_instruction=AI_SUMMARY_SYSTEM,
        )
        return summary.strip()
    except Exception as e:
        print(f"[analytics_service] LLM summary generation failed: {e}")
        # Fallback summary
        if bugs_total == 0 and prs_reviewed == 0:
            return f"No pull request or bug triage activity recorded for {repo_key} in the last {period}. Velocity tracking is idle."
        return (
            f"Over the last {period}, the team processed {prs_reviewed} PR reviews with an average turnaround of {avg_turnaround}h. "
            f"There are currently {bugs_open} open bugs ({bugs_by_sev['high']} high severity) out of {bugs_total} triaged ({bugs_resolved_pct}% resolved). "
            f"Top code churn files include {top_files_summary}."
        )


def set_bug_status(bug_id: str, status: str) -> dict:
    """Updates bug status ('open' or 'resolved') so team leads can track progress."""
    clean_status = status.strip().lower()
    if clean_status not in ("open", "resolved"):
        raise ValueError("Status must be 'open' or 'resolved'.")

    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE bugs SET status = %s WHERE bug_id = %s RETURNING bug_id, status",
                (clean_status, bug_id),
            )
            row = cur.fetchone()
        conn.commit()
        if not row:
            raise ValueError(f"Bug {bug_id} not found.")
        return {"bug_id": row[0], "status": row[1]}
    finally:
        conn.close()
